export const userData = [
	{
		name: 'Jan',
		'Active User': 4521,
	},
	{
		name: 'Feb',
		'Active User': 3217,
	},
	{
		name: 'Mar',
		'Active User': 5225,
	},
	{
		name: 'Apr',
		'Active User': 4252,
	},
	{
		name: 'May',
		'Active User': 3211,
	},
	{
		name: 'Jun',
		'Active User': 7111,
	},
	{
		name: 'Jul',
		'Active User': 1911,
	},
	{
		name: 'Aug',
		'Active User': 5242,
	},
	{
		name: 'Sep',
		'Active User': 3575,
	},
	{
		name: 'Oct',
		'Active User': 6886,
	},
	{
		name: 'Nov',
		'Active User': 4531,
	},
	{
		name: 'Dec',
		'Active User': 7817,
	},
];

export const productData = [
	{
		name: 'Jan',
		'Sales ': 4521,
	},
	{
		name: 'Feb',
		'Sales ': 3217,
	},
	{
		name: 'Mar',
		'Sales ': 5225,
	},
];

//---------

export const userRows = [
	{
		id: 1,
		username: 'Mustafa Ozdemir',
		avatar: 'https://cdn4.iconfinder.com/data/icons/small-n-flat/24/user-alt-512.png',
		email: 'mustafadennisozdemir@gmail.com',
		status: 'active',
		transaction: '$120.00',
	},
	{
		id: 2,
		username: 'Mustafa Ozdemir',
		avatar: 'https://cdn4.iconfinder.com/data/icons/small-n-flat/24/user-alt-512.png',
		email: 'mustafadennisozdemir@gmail.com',
		status: 'active',
		transaction: '$120.00',
	},
	{
		id: 3,
		username: 'Mustafa Ozdemir',
		avatar: 'https://cdn4.iconfinder.com/data/icons/small-n-flat/24/user-alt-512.png',
		email: 'mustafadennisozdemir@gmail.com',
		status: 'active',
		transaction: '$120.00',
	},
	{
		id: 4,
		username: 'Mustafa Ozdemir',
		avatar: 'https://cdn4.iconfinder.com/data/icons/small-n-flat/24/user-alt-512.png',
		email: 'mustafadennisozdemir@gmail.com',
		status: 'active',
		transaction: '$120.00',
	},
	{
		id: 5,
		username: 'Mustafa Ozdemir',
		avatar: 'https://cdn4.iconfinder.com/data/icons/small-n-flat/24/user-alt-512.png',
		email: 'mustafadennisozdemir@gmail.com',
		status: 'active',
		transaction: '$120.00',
	},
	{
		id: 6,
		username: 'Mustafa Ozdemir',
		avatar: 'https://cdn4.iconfinder.com/data/icons/small-n-flat/24/user-alt-512.png',
		email: 'mustafadennisozdemir@gmail.com',
		status: 'active',
		transaction: '$120.00',
	},
	{
		id: 7,
		username: 'Mustafa Ozdemir',
		avatar: 'https://cdn4.iconfinder.com/data/icons/small-n-flat/24/user-alt-512.png',
		email: 'mustafadennisozdemir@gmail.com',
		status: 'active',
		transaction: '$120.00',
	},
	{
		id: 8,
		username: 'Mustafa Ozdemir',
		avatar: 'https://cdn4.iconfinder.com/data/icons/small-n-flat/24/user-alt-512.png',
		email: 'mustafadennisozdemir@gmail.com',
		status: 'active',
		transaction: '$120.00',
	},
	{
		id: 9,
		username: 'Mustafa Ozdemir',
		avatar: 'https://cdn4.iconfinder.com/data/icons/small-n-flat/24/user-alt-512.png',
		email: 'mustafadennisozdemir@gmail.com',
		status: 'active',
		transaction: '$120.00',
	},
	{
		id: 10,
		username: 'Mustafa Ozdemir',
		avatar: 'https://cdn4.iconfinder.com/data/icons/small-n-flat/24/user-alt-512.png',
		email: 'mustafadennisozdemir@gmail.com',
		status: 'active',
		transaction: '$120.00',
	},
	{
		id: 11,
		username: 'Mustafa Ozdemir',
		avatar: 'https://cdn4.iconfinder.com/data/icons/small-n-flat/24/user-alt-512.png',
		email: 'mustafadennisozdemir@gmail.com',
		status: 'active',
		transaction: '$120.00',
	},
	{
		id: 12,
		username: 'Mustafa Ozdemir',
		avatar: 'https://cdn4.iconfinder.com/data/icons/small-n-flat/24/user-alt-512.png',
		email: 'mustafadennisozdemir@gmail.com',
		status: 'active',
		transaction: '$120.00',
	},
	{
		id: 13,
		username: 'Mustafa Ozdemir',
		avatar: 'https://cdn4.iconfinder.com/data/icons/small-n-flat/24/user-alt-512.png',
		email: 'mustafadennisozdemir@gmail.com',
		status: 'active',
		transaction: '$120.00',
	},
];
export const productRows = [
	{
		id: 1,
		name: 'Apple Airpods',
		img: 'https://lcdn.altex.ro/media/catalog/product/C/A/CASAIRPODS_313d0f7a.jpg',
		stock: 152,
		status: 'active',
		price: '$199.00',
	},
	{
		id: 2,
		name: 'Apple Airpods',
		img: 'https://lcdn.altex.ro/media/catalog/product/C/A/CASAIRPODS_313d0f7a.jpg',
		stock: 152,
		status: 'active',
		price: '$199.00',
	},
	{
		id: 3,
		name: 'Apple Airpods',
		img: 'https://lcdn.altex.ro/media/catalog/product/C/A/CASAIRPODS_313d0f7a.jpg',
		stock: 152,
		status: 'active',
		price: '$199.00',
	},
	{
		id: 4,
		name: 'Apple Airpods',
		img: 'https://lcdn.altex.ro/media/catalog/product/C/A/CASAIRPODS_313d0f7a.jpg',
		stock: 152,
		status: 'active',
		price: '$199.00',
	},
	{
		id: 5,
		name: 'Apple Airpods',
		img: 'https://lcdn.altex.ro/media/catalog/product/C/A/CASAIRPODS_313d0f7a.jpg',
		stock: 152,
		status: 'active',
		price: '$199.00',
	},
	{
		id: 6,
		name: 'Apple Airpods',
		img: 'https://lcdn.altex.ro/media/catalog/product/C/A/CASAIRPODS_313d0f7a.jpg',
		stock: 152,
		status: 'active',
		price: '$199.00',
	},
	{
		id: 7,
		name: 'Apple Airpods',
		img: 'https://lcdn.altex.ro/media/catalog/product/C/A/CASAIRPODS_313d0f7a.jpg',
		stock: 152,
		status: 'active',
		price: '$199.00',
	},
	{
		id: 8,
		name: 'Apple Airpods',
		img: 'https://lcdn.altex.ro/media/catalog/product/C/A/CASAIRPODS_313d0f7a.jpg',
		stock: 152,
		status: 'active',
		price: '$199.00',
	},
	{
		id: 9,
		name: 'Apple Airpods',
		img: 'https://lcdn.altex.ro/media/catalog/product/C/A/CASAIRPODS_313d0f7a.jpg',
		stock: 152,
		status: 'active',
		price: '$199.00',
	},
	{
		id: 10,
		name: 'Apple Airpods',
		img: 'https://lcdn.altex.ro/media/catalog/product/C/A/CASAIRPODS_313d0f7a.jpg',
		stock: 152,
		status: 'active',
		price: '$199.00',
	},
	{
		id: 11,
		name: 'Apple Airpods',
		img: 'https://lcdn.altex.ro/media/catalog/product/C/A/CASAIRPODS_313d0f7a.jpg',
		stock: 152,
		status: 'active',
		price: '$199.00',
	},
	{
		id: 12,
		name: 'Apple Airpods',
		img: 'https://lcdn.altex.ro/media/catalog/product/C/A/CASAIRPODS_313d0f7a.jpg',
		stock: 152,
		status: 'active',
		price: '$199.00',
	},
	{
		id: 13,
		name: 'Apple Airpods',
		img: 'https://lcdn.altex.ro/media/catalog/product/C/A/CASAIRPODS_313d0f7a.jpg',
		stock: 152,
		status: 'active',
		price: '$199.00',
	},
];
